# Generated by Django 3.2.14 on 2022-08-02 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата записи'),
        ),
    ]
