# Generated by Django 3.2.14 on 2022-08-02 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_alter_record_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата записи'),
        ),
    ]
