# Generated by Django 3.2.14 on 2022-08-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_record_kasha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='kasha',
            field=models.BooleanField(),
        ),
    ]
