# Generated by Django 3.2.14 on 2022-08-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_alter_record_kasha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='kasha',
            field=models.BooleanField(default=False, verbose_name='Каша ли это?'),
        ),
    ]
